---
- name: Prevent the iptables-peristent install dialog
  shell: echo {{ item }} | debconf-set-selections
  with_items:
  - iptables-persistent iptables-persistent/autosave_v4 boolean false
  - iptables-persistent iptables-persistent/autosave_v6 boolean false
- name: Ensure iptables-persistent is installed
  apt: pkg=iptables-persistent state=present update_cache=yes cache_valid_time=3600
- name: Update iptables rules
  copy: src=rules.v4 dest=/etc/iptables/ backup=yes
  sudo: yes
  notify:
    - restart iptables-persistent